include: package:flutter_lints/flutter.yaml

linter:
  rules:
    sort_constructors_first: true
    prefer_single_quotes: true
    always_put_required_named_parameters_first: true
    always_use_package_imports: false
    prefer_relative_imports: true
    depend_on_referenced_packages: false
    require_trailing_commas: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    todo: info